<style>
@media print {
    @page {
        size: landscape;
    }
}
</style>

<div style="text-align: center; border: 2px solid #000; padding: 50px; margin: 20px;">
    <h1 style="font-size: 30px;">Calidad de Software con modelos predictivos</h1>
    <br>
    <h2 style="font-size: 24px;">Proyecto de Regresión</h2>
    <br><br>
    <p style="font-size: 18px;"><strong>Presenta:</strong></p>
    <p style="font-size: 20px;">Marvin Salvador Bacilio Anota</p>
    <br>
    <p style="font-size: 18px;"><strong>Profesora:</strong></p>
    <p style="font-size: 20px;">Dra. Verónica Rodríguez López</p>
    <br><br>
    <p style="font-size: 16px;">Fecha: 6 de febrero de 2026</p>
</div>

<div style="page-break-after: always;"></div>

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# -------------------------
# 1. Cargar datos (Windows)
# -------------------------
ruta = r"C:\Users\Marvi\OneDrive\Documentos\GitHub\Proyecto-Veronica\fp.csv"
df = pd.read_csv(ruta)


# ---------------------------------------------------------
# 2. Vista rápida
# ---------------------------------------------------------

In [5]:


display(df.head())
print("Dimensiones:", df.shape)

,id,Project,TeamExp,ManagerExp,YearEnd,Length,Effort,Transactions,Entities,PointsNonAdjust,Adjustment,PointsAjust,Language
0,1,1,1,4,85,12,5152,253,52,305,34,302,1
1,2,2,0,0,86,4,5635,197,124,321,33,315,1
2,3,3,4,4,85,1,805,40,60,100,18,83,1
3,4,4,0,0,86,5,3829,200,119,319,30,303,1
4,5,5,0,0,86,4,2149,140,94,234,24,208,1

Dimensiones: (81, 13)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               81 non-null     int64
 1   Project          81 non-null     int64
 2   TeamExp          81 non-null     int64
 3   ManagerExp       81 non-null     int64
 4   YearEnd          81 non-null     int64
 5   Length           81 non-null     int64
 6   Effort           81 non-null     int64
 7   Transactions     81 non-null     int64
 8   Entities         81 non-null     int64
 9   PointsNonAdjust  81 non-null     int64
 10  Adjustment       81 non-null     int64
 11  PointsAjust      81 non-null     int64
 12  Language         81 non-null     int64
dtypes: int64(13)
memory usage: 8.4 KB

In [7]:
num_cols = df.select_dtypes(include=["int64", "float64"]).columns
cat_cols = df.select_dtypes(include=["object", "category"]).columns

print("Numéricas:", list(num_cols))
print("Categóricas:", list(cat_cols))

Numéricas: ['id', 'Project', 'TeamExp', 'ManagerExp', 'YearEnd', 'Length', 'Effort', 'Transactions', 'Entities', 'PointsNonAdjust', 'Adjustment', 'PointsAjust', 'Language']
Categóricas: []

Dato los tipos de datos, se puede observar que no existe una columna objetivo de tipo categorica. 
Se puede decir que esto es un problema de regresión

In [8]:

# Dimensiones
print("Dimensiones del dataset:", df.shape)
# Estadísticos descriptivos
df.describe(include="all")

Dimensiones del dataset: (81, 13)

,id,Project,TeamExp,ManagerExp,YearEnd,Length,Effort,Transactions,Entities,PointsNonAdjust,Adjustment,PointsAjust,Language
count,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000,81.000000
mean,41.000000,41.000000,2.185185,2.530864,85.740741,11.666667,5046.308642,182.123457,122.333333,304.456790,27.629630,289.234568,1.555556
std,23.526581,23.526581,1.415195,1.643825,1.222475,7.424621,4418.767228,144.035098,84.882124,180.210159,10.591795,185.761088,0.707107
min,1.000000,1.000000,-1.000000,-1.000000,82.000000,1.000000,546.000000,9.000000,7.000000,73.000000,5.000000,62.000000,1.000000
25%,21.000000,21.000000,1.000000,1.000000,85.000000,6.000000,2352.000000,88.000000,57.000000,176.000000,20.000000,152.000000,1.000000
50%,41.000000,41.000000,2.000000,3.000000,86.000000,10.000000,3647.000000,140.000000,99.000000,266.000000,28.000000,255.000000,1.000000
75%,61.000000,61.000000,4.000000,4.000000,87.000000,14.000000,5922.000000,224.000000,169.000000,384.000000,35.000000,351.000000,2.000000
max,81.000000,81.000000,4.000000,7.000000,88.000000,39.000000,23940.000000,886.000000,387.000000,1127.000000,52.000000,1116.000000,3.000000

# =============================================================================
# 2. PREPROCESAMIENTO
# =============================================================================

In [9]:
columnas_a_eliminar = ['id', 'Project', 'YearEnd', 'Language']
df.drop(columns=[col for col in columnas_a_eliminar if col in df.columns], inplace=True)